import type { PosAccessRoleCode, PosPermissionCode } from "./auth.types";

export const CASHIER_PERMISSION_CODES: PosPermissionCode[] = [
  "POS_OPEN_SESSION",
  "POS_CLOSE_OWN_SESSION",
  "POS_VIEW_POS_SCREEN",
  "POS_SCAN_BARCODE",
  "POS_SEARCH_ITEM",
  "POS_ADD_ITEM_TO_CART",
  "POS_UPDATE_ITEM_QUANTITY",
  "POS_REMOVE_ITEM_FROM_CART",
  "POS_HOLD_SALE",
  "POS_RESUME_OWN_HELD_SALE",
  "POS_VOID_DRAFT_SALE",
  "POS_COMPLETE_SALE",
  "POS_SELECT_PAYMENT_METHOD",
  "POS_PRINT_RECEIPT",
  "POS_VIEW_OWN_SESSION_REPORT",
  "POS_VIEW_COMPLETED_SALES",
  "POS_CHANGE_UNIT_PRICE",
  "RST_VIEW_TABLE_SCREEN",
  "RST_OPEN_TABLE_ORDER",
  "RST_CREATE_TAKEAWAY_ORDER",
  "RST_CREATE_DELIVERY_ORDER",
  "RST_SEND_KOT",
  "RST_APPLY_SERVICE_CHARGE",
  "RST_COMPLETE_RESTAURANT_PAYMENT",
  "RST_PRINT_PRE_BILL",
];

export const KITCHEN_PERMISSION_CODES: PosPermissionCode[] = [
  "RST_VIEW_KITCHEN_SCREEN",
  "RST_UPDATE_KITCHEN_STATUS",
  "RST_CANCEL_KOT_ITEM",
  "RST_MARK_ITEM_UNAVAILABLE",
];

export const WAITER_PERMISSION_CODES: PosPermissionCode[] = [
  "RST_VIEW_TABLE_SCREEN",
  "RST_OPEN_TABLE_ORDER",
  "RST_SEND_KOT",
  "RST_VIEW_WAITER_ORDERS",
  "RST_UPDATE_WAITER_ORDER_STATUS",
  "POS_HOLD_SALE",
  "POS_SEARCH_ITEM",
  "POS_ADD_ITEM_TO_CART",
  "POS_UPDATE_ITEM_QUANTITY",
  "POS_REMOVE_ITEM_FROM_CART",
];

export const ACCOUNTANT_PERMISSION_CODES: PosPermissionCode[] = [
  "POS_VIEW_COMPLETED_SALES",
  "POS_VIEW_PENDING_ACCOUNTING",
  "POS_VIEW_POS_INVOICE_DETAILS",
  "POS_VIEW_POS_PAYMENTS",
  "POS_VIEW_POS_INVENTORY_MOVEMENTS",
  "POS_VIEW_SESSIONS",
  "POS_VIEW_SESSION_REPORT",
  "POS_APPROVE_ACCOUNTING",
  "POS_REJECT_ACCOUNTING",
  "POS_POST_BY_INVOICE",
  "POS_POST_BY_SESSION",
  "POS_VIEW_POS_REPORTS",
  "POS_EXPORT_POS_REPORTS",
  "VIEW_JOURNAL_ENTRIES",
  "VIEW_GENERAL_LEDGER",
  "VIEW_INVENTORY_MOVEMENTS",
  "POS_CREDIT_SALE",
  "POS_SELL_NEGATIVE_STOCK",
  "POS_CHANGE_UNIT_PRICE",
  "RST_TRANSFER_TABLE",
  "RST_MERGE_TABLES",
  "RST_SPLIT_BILL",
  "RST_ASSIGN_DRIVER",
  "RST_CANCEL_KOT_ITEM",
  "RST_REPRINT_KOT",
  "RST_VIEW_KITCHEN_SCREEN",
  "RST_UPDATE_KITCHEN_STATUS",
  "RST_MARK_ITEM_UNAVAILABLE",
  "RST_OVERRIDE_SERVICE_CHARGE",
  "RST_CANCEL_RESTAURANT_ORDER",
  "RST_VIEW_RESTAURANT_REPORTS",
  "POS_CORRECT_ORDER_TYPE",
  "POS_APPROVE_CORRECTION",
  "POS_REOPEN_SESSION",
];

export const POS_ROLE_ROUTE_ACCESS: Record<PosAccessRoleCode, string[]> = {
  CASHIER: [
    "/pos/register",
    "/pos/session",
    "/pos/sessions",
    "/pos/held-sales",
    "/pos/receipt",
    "/pos/tables",
    "/pos/delivery",
    "/pos/returns",
  ],
  KITCHEN: [],
  WAITER: ["/pos/waiter/tables", "/pos/waiter/order", "/pos/waiter/orders"],
  ACCOUNTANT: [
    "/dashboard",
    "/accounts",
    "/sales-receivables",
    "/journal-entries",
    "/general-ledger",
    "/inventory",
    "/pos/accounting-review",
    "/pos/sessions",
    "/pos/completed-sales",
    "/pos/delivery",
    "/pos/reports",
    "/pos/settings",
  ],
};

export const POS_ROLE_PERMISSIONS: Record<PosAccessRoleCode, PosPermissionCode[]> = {
  CASHIER: CASHIER_PERMISSION_CODES,
  ACCOUNTANT: ACCOUNTANT_PERMISSION_CODES,
  KITCHEN: KITCHEN_PERMISSION_CODES,
  WAITER: WAITER_PERMISSION_CODES,
};

export const ALL_POS_PERMISSION_CODES: PosPermissionCode[] = Array.from(
  new Set([
    ...CASHIER_PERMISSION_CODES,
    ...ACCOUNTANT_PERMISSION_CODES,
    ...KITCHEN_PERMISSION_CODES,
    ...WAITER_PERMISSION_CODES,
  ]),
);

export function uniqueRoutes(routes: string[]) {
  return Array.from(new Set(routes));
}
