import { BadRequestException, ConflictException, Injectable, UnauthorizedException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { PosAccessRoleCode, PosPermissionCode, Prisma, UserRole } from '../../../generated/prisma';
import * as bcrypt from 'bcrypt';

import { PrismaService } from '../../../common/prisma/prisma.service';
import {
  ACCOUNTANT_PERMISSION_CODES,
  ALL_POS_PERMISSION_CODES,
  CASHIER_PERMISSION_CODES,
  POS_ROLE_PERMISSIONS,
  POS_ROLE_ROUTE_ACCESS,
  uniqueRoutes,
} from './access-control.constants';
import { AUTH_SESSION_TTL, AUTH_SESSION_TTL_SECONDS } from './auth.constants';
import type { AuthorizedUser } from './auth.types';
import { LoginDto, RegisterDto } from './dto/auth.dto';

const POS_ACCESS_ROLE_NAMES: Record<PosAccessRoleCode, string> = {
  CASHIER: 'Cashier',
  ACCOUNTANT: 'Accountant',
  KITCHEN: 'Kitchen',
  WAITER: 'Waiter',
  MARKET_CASHIER: 'Market Cashier',
  MARKET_REP: 'Market Sales Rep',
};

const POS_ACCESS_ROLE_DESCRIPTIONS: Record<PosAccessRoleCode, string> = {
  CASHIER: 'Operational restaurant POS sales access limited to cashier workflows.',
  ACCOUNTANT: 'POS accounting review, reporting, and posting access.',
  KITCHEN: 'Kitchen display only — view and update order preparation status.',
  WAITER: 'Table ordering and send-to-kitchen only — no payment.',
  MARKET_CASHIER: 'Operational market/retail POS sales access limited to market cashier workflows.',
  MARKET_REP: 'Market field sales rep — sell on credit and collect receivables for assigned destination markets.',
};

const POS_PERMISSION_METADATA: Record<PosPermissionCode, { name: string; description: string }> = {
  POS_OPEN_SESSION: { name: 'Open POS session', description: 'Open a new POS session.' },
  POS_CLOSE_OWN_SESSION: { name: 'Close own POS session', description: 'Close the cashier’s own session.' },
  POS_VIEW_POS_SCREEN: { name: 'View POS sales screen', description: 'Access the operational POS register.' },
  POS_SCAN_BARCODE: { name: 'Scan barcode', description: 'Scan POS items by barcode.' },
  POS_SEARCH_ITEM: { name: 'Search item', description: 'Search POS items by code or name.' },
  POS_ADD_ITEM_TO_CART: { name: 'Add item to cart', description: 'Add items into the POS cart.' },
  POS_UPDATE_ITEM_QUANTITY: { name: 'Update item quantity', description: 'Change cart line quantities before completion.' },
  POS_REMOVE_ITEM_FROM_CART: { name: 'Remove item from cart', description: 'Remove POS cart lines before completion.' },
  POS_HOLD_SALE: { name: 'Hold sale', description: 'Save a draft POS sale as held.' },
  POS_RESUME_OWN_HELD_SALE: { name: 'Resume own held sale', description: 'Resume held sales within the cashier ownership scope.' },
  POS_VOID_DRAFT_SALE: { name: 'Void draft sale', description: 'Void draft or held POS sales before completion.' },
  POS_COMPLETE_SALE: { name: 'Complete sale', description: 'Complete and finalize a POS sale.' },
  POS_SELECT_PAYMENT_METHOD: { name: 'Select payment method', description: 'Choose allowed POS tender methods.' },
  POS_PRINT_RECEIPT: { name: 'Print receipt', description: 'Print a POS receipt after completion.' },
  POS_VIEW_OWN_SESSION_REPORT: { name: 'View own session report', description: 'View the current cashier session summary.' },
  POS_VIEW_COMPLETED_SALES: { name: 'View completed sales', description: 'Review completed POS sales.' },
  POS_VIEW_PENDING_ACCOUNTING: { name: 'View pending accounting', description: 'View POS sales awaiting accounting review.' },
  POS_VIEW_POS_INVOICE_DETAILS: { name: 'View POS invoice details', description: 'Inspect full POS invoice details.' },
  POS_VIEW_POS_PAYMENTS: { name: 'View POS payments', description: 'Inspect POS payment allocations.' },
  POS_VIEW_POS_INVENTORY_MOVEMENTS: { name: 'View POS inventory movements', description: 'Review inventory movements generated by POS.' },
  POS_VIEW_SESSIONS: { name: 'View POS sessions', description: 'Review POS sessions.' },
  POS_VIEW_SESSION_REPORT: { name: 'View POS session reports', description: 'View POS session reports across cashiers.' },
  POS_APPROVE_ACCOUNTING: { name: 'Approve accounting', description: 'Approve POS documents for accounting posting.' },
  POS_REJECT_ACCOUNTING: { name: 'Reject accounting', description: 'Reject POS documents during accounting review.' },
  POS_POST_BY_INVOICE: { name: 'Post by invoice', description: 'Post POS accounting by invoice.' },
  POS_POST_BY_SESSION: { name: 'Post by session', description: 'Post POS accounting by session.' },
  POS_VIEW_POS_REPORTS: { name: 'View POS reports', description: 'Access POS reporting screens.' },
  POS_EXPORT_POS_REPORTS: { name: 'Export POS reports', description: 'Export POS reports to PDF or Excel.' },
  VIEW_JOURNAL_ENTRIES: { name: 'View journal entries', description: 'Access journal entries generated from POS posting.' },
  VIEW_GENERAL_LEDGER: { name: 'View general ledger', description: 'Access the general ledger workspace.' },
  VIEW_INVENTORY_MOVEMENTS: { name: 'View inventory movements', description: 'Access inventory movement inquiry routes.' },
  POS_CREDIT_SALE: { name: 'POS credit sale', description: 'Allow POS sales with unpaid balance when permitted by policy.' },
  POS_SELL_NEGATIVE_STOCK: { name: 'POS negative stock', description: 'Allow POS inventory issues despite negative stock safeguards.' },
  POS_CHANGE_UNIT_PRICE: { name: 'Change POS line price', description: 'Override item default sale price at the POS cart.' },
  RST_VIEW_TABLE_SCREEN: { name: 'View restaurant tables', description: 'View the dine-in table grid and statuses.' },
  RST_OPEN_TABLE_ORDER: { name: 'Open table order', description: 'Open or link a POS order to a restaurant table.' },
  RST_TRANSFER_TABLE: { name: 'Transfer table order', description: 'Move an active order from one table to another.' },
  RST_MERGE_TABLES: { name: 'Merge tables', description: 'Merge multiple restaurant tables into one bill.' },
  RST_SPLIT_BILL: { name: 'Split bill', description: 'Split a restaurant bill by guest, item, amount, or percentage.' },
  RST_CREATE_TAKEAWAY_ORDER: { name: 'Create takeaway order', description: 'Create takeaway restaurant orders.' },
  RST_CREATE_DELIVERY_ORDER: { name: 'Create delivery order', description: 'Create restaurant delivery orders.' },
  RST_ASSIGN_DRIVER: { name: 'Assign driver', description: 'Assign a driver to a delivery order.' },
  RST_SEND_KOT: { name: 'Send kitchen ticket', description: 'Send restaurant items to kitchen production.' },
  RST_CANCEL_KOT_ITEM: { name: 'Cancel kitchen item', description: 'Cancel or void an item that has already been sent to the kitchen.' },
  RST_REPRINT_KOT: { name: 'Reprint kitchen ticket', description: 'Reprint a kitchen order ticket when authorized.' },
  RST_VIEW_KITCHEN_SCREEN: { name: 'View kitchen screen', description: 'View kitchen orders and their live statuses.' },
  RST_UPDATE_KITCHEN_STATUS: { name: 'Update kitchen status', description: 'Move kitchen items or tickets through preparation statuses.' },
  RST_MARK_ITEM_UNAVAILABLE: { name: 'Mark menu item unavailable', description: 'Temporarily mark a restaurant item unavailable for ordering.' },
  RST_APPLY_SERVICE_CHARGE: { name: 'Apply service charge', description: 'Apply service charges to restaurant orders.' },
  RST_OVERRIDE_SERVICE_CHARGE: { name: 'Override service charge', description: 'Override the default restaurant service charge.' },
  RST_PRINT_PRE_BILL: { name: 'Print pre-bill', description: 'Print a pre-bill for a restaurant table before payment.' },
  RST_COMPLETE_RESTAURANT_PAYMENT: { name: 'Complete restaurant payment', description: 'Complete dine-in, takeaway, or delivery restaurant payments.' },
  RST_CANCEL_RESTAURANT_ORDER: { name: 'Cancel restaurant order', description: 'Cancel a restaurant order under controlled workflow.' },
  RST_VIEW_RESTAURANT_REPORTS: { name: 'View restaurant reports', description: 'Access restaurant-specific reporting and summaries.' },
  RST_VIEW_WAITER_ORDERS: { name: 'View waiter order board', description: 'View dine-in order tracking for waiters.' },
  RST_UPDATE_WAITER_ORDER_STATUS: { name: 'Update waiter order status', description: 'Advance dine-in orders through waiter service statuses.' },
  POS_CORRECT_ORDER_TYPE: { name: 'Correct order type', description: 'Correct the restaurant order type after creation when allowed.' },
  POS_APPROVE_CORRECTION: { name: 'Approve order correction', description: 'Approve a restaurant order-type correction request.' },
  POS_REOPEN_SESSION: { name: 'Reopen POS session', description: 'Reopen a submitted or closed POS session when authorized.' },
  POS_MARKET_VIEW_RECEIVABLES: {
    name: 'View market receivables',
    description: 'View outstanding balances for market destination customers.',
  },
  POS_MARKET_COLLECT_RECEIVABLE: {
    name: 'Collect market receivables',
    description: 'Record customer receipts against market POS open invoices.',
  },
  POS_MARKET_MANAGE_REP_LOADS: {
    name: 'Manage rep car loads',
    description: 'Create and post تحميل سيارة documents from main warehouse to rep car stock.',
  },
  POS_MARKET_REP_STOCKTAKE: {
    name: 'Rep car stocktake',
    description: 'Create and post monthly جرد for goods on rep cars.',
  },
  POS_MARKET_AMEND_SALE: {
    name: 'Amend market POS sale',
    description: 'Amend a completed market POS invoice before accounting posting while the session is open.',
  },
};

@Injectable()
export class AuthService {
  constructor(
    private prisma: PrismaService,
    private jwtService: JwtService,
  ) {}

  async register(dto: RegisterDto) {
    const requestedPosRoles = this.normalizePosRoles(dto.posRoles);
    const salesRepId = await this.resolveRegisterSalesRepId(dto.salesRepId, requestedPosRoles);

    return this.createUserWithPosAccess({
      username: dto.username,
      email: dto.email,
      password: dto.password,
      name: dto.name,
      posRoles: requestedPosRoles,
      salesRepId,
    });
  }

  async createMarketRepUserForSalesRep(
    salesRepId: string,
    dto: { username: string; email: string; password: string; name?: string },
  ) {
    const rep = await this.prisma.salesRepresentative.findFirst({
      where: { id: salesRepId.trim(), status: 'ACTIVE' },
      select: { id: true },
    });
    if (!rep) {
      throw new BadRequestException('Sales representative was not found or is inactive.');
    }

    return this.createUserWithPosAccess({
      username: dto.username,
      email: dto.email,
      password: dto.password,
      name: dto.name,
      posRoles: [PosAccessRoleCode.MARKET_REP],
      salesRepId: rep.id,
    });
  }

  private async createUserWithPosAccess(input: {
    username: string;
    email: string;
    password: string;
    name?: string;
    posRoles: PosAccessRoleCode[];
    salesRepId?: string | null;
  }) {
    await this.ensurePosAccessBaseline();

    const email = input.email.trim().toLowerCase();
    const username = input.username.trim().toLowerCase();
    const requestedPosRoles = input.posRoles;

    const [existingEmailUser, existingUsernameUser] = await Promise.all([
      this.prisma.user.findUnique({ where: { email } }),
      this.prisma.user.findUnique({ where: { username } }),
    ]);

    if (existingEmailUser) {
      throw new ConflictException('A user with this email already exists.');
    }
    if (existingUsernameUser) {
      throw new ConflictException('A user with this username already exists.');
    }

    const hashedPassword = await bcrypt.hash(input.password, 10);
    const roleRecords = requestedPosRoles.length
      ? await this.prisma.posAccessRole.findMany({
          where: { code: { in: requestedPosRoles } },
          select: { id: true, code: true },
        })
      : [];

    const user = await this.prisma.user.create({
      data: {
        username,
        email,
        password: hashedPassword,
        name: input.name?.trim() || null,
        role: UserRole.USER,
        salesRepId: input.salesRepId ?? null,
        posAccessRoles: roleRecords.length
          ? {
              create: roleRecords.map((roleRecord) => ({
                roleId: roleRecord.id,
              })),
            }
          : undefined,
      },
      include: this.userAccessInclude(),
    });

    return this.toRegisteredUserResponse(user);
  }

  private toRegisteredUserResponse(
    user: Prisma.UserGetPayload<{ include: ReturnType<AuthService['userAccessInclude']> }>,
  ) {
    const accessUser = this.buildAuthorizedUser(user);
    return {
      id: user.id,
      username: user.username,
      email: user.email,
      name: user.name,
      role: user.role,
      isActive: user.isActive,
      posRoles: accessUser.posRoles,
      permissions: accessUser.permissions,
      allowedRoutes: accessUser.allowedRoutes,
      defaultRoute: accessUser.defaultRoute,
      salesRepId: accessUser.salesRepId,
      createdAt: user.createdAt,
      updatedAt: user.updatedAt,
    };
  }

  async login(dto: LoginDto) {
    await this.ensurePosAccessBaseline();

    const identifier = dto.username.trim().toLowerCase();
    const user = await this.prisma.user.findFirst({
      where: {
        OR: [{ username: identifier }, { email: identifier }],
      },
      include: this.userAccessInclude(),
    });

    if (!user) {
      throw new UnauthorizedException('Invalid credentials');
    }
    if (!user.isActive) {
      throw new UnauthorizedException('This user account is inactive.');
    }

    const isPasswordValid = await bcrypt.compare(dto.password, user.password);
    if (!isPasswordValid) {
      throw new UnauthorizedException('Invalid credentials');
    }

    const accessUser = this.buildAuthorizedUser(user);
    const payload = {
      sub: user.id,
      username: user.username,
      email: user.email,
      name: user.name,
      role: user.role,
      isActive: user.isActive,
      posRoles: accessUser.posRoles,
      permissions: accessUser.permissions,
      allowedRoutes: accessUser.allowedRoutes,
      defaultRoute: accessUser.defaultRoute,
      isCashierOnly: accessUser.isCashierOnly,
      isMarketCashierOnly: accessUser.isMarketCashierOnly,
      isMarketRepOnly: accessUser.isMarketRepOnly,
      isMarketPosOperatorOnly: accessUser.isMarketPosOperatorOnly,
      salesRepId: accessUser.salesRepId,
      isKitchenOnly: accessUser.isKitchenOnly,
      isWaiterOnly: accessUser.isWaiterOnly,
    };

    const accessToken = await this.jwtService.signAsync(payload, {
      expiresIn: AUTH_SESSION_TTL,
    });
    const expiresAt = new Date(Date.now() + AUTH_SESSION_TTL_SECONDS * 1000);

    return {
      access_token: accessToken,
      expires_in: AUTH_SESSION_TTL_SECONDS,
      expires_at: expiresAt.toISOString(),
      user: {
        id: user.id,
        username: user.username,
        email: user.email,
        name: user.name,
        role: user.role,
        posRoles: accessUser.posRoles,
        permissions: accessUser.permissions,
        allowedRoutes: accessUser.allowedRoutes,
        defaultRoute: accessUser.defaultRoute,
        salesRepId: accessUser.salesRepId,
      },
    };
  }

  private normalizePosRoles(posRoles?: string[]) {
    const normalized = (posRoles ?? [])
      .map((role) => role.trim().toUpperCase())
      .filter(
        (role): role is PosAccessRoleCode =>
          role === 'CASHIER' ||
          role === 'ACCOUNTANT' ||
          role === 'KITCHEN' ||
          role === 'WAITER' ||
          role === 'MARKET_CASHIER' ||
          role === 'MARKET_REP',
      );

    return normalized.length ? Array.from(new Set(normalized)) : [PosAccessRoleCode.ACCOUNTANT];
  }

  private async resolveRegisterSalesRepId(
    salesRepId: string | undefined,
    posRoles: PosAccessRoleCode[],
  ) {
    const normalizedId = salesRepId?.trim();
    if (!normalizedId) {
      if (posRoles.includes(PosAccessRoleCode.MARKET_REP)) {
        throw new BadRequestException('MARKET_REP users require an active salesRepId.');
      }
      return null;
    }

    const salesRep = await this.prisma.salesRepresentative.findFirst({
      where: { id: normalizedId, status: 'ACTIVE' },
      select: { id: true },
    });
    if (!salesRep) {
      throw new BadRequestException('Sales representative was not found or is inactive.');
    }
    return salesRep.id;
  }

  private async ensurePosAccessBaseline() {
    await this.ensurePosAccessRoleEnumValues();

    await this.prisma.$transaction(async (tx) => {
      for (const roleCode of [
        PosAccessRoleCode.CASHIER,
        PosAccessRoleCode.ACCOUNTANT,
        PosAccessRoleCode.KITCHEN,
        PosAccessRoleCode.WAITER,
        PosAccessRoleCode.MARKET_CASHIER,
        PosAccessRoleCode.MARKET_REP,
      ] as const) {
        await tx.posAccessRole.upsert({
          where: { code: roleCode },
          update: {
            name: POS_ACCESS_ROLE_NAMES[roleCode],
            description: POS_ACCESS_ROLE_DESCRIPTIONS[roleCode],
            isActive: true,
          },
          create: {
            code: roleCode,
            name: POS_ACCESS_ROLE_NAMES[roleCode],
            description: POS_ACCESS_ROLE_DESCRIPTIONS[roleCode],
            isActive: true,
          },
        });
      }

      for (const permissionCode of ALL_POS_PERMISSION_CODES) {
        const metadata = POS_PERMISSION_METADATA[permissionCode];
        await tx.posPermission.upsert({
          where: { code: permissionCode },
          update: { name: metadata.name, description: metadata.description },
          create: {
            code: permissionCode,
            name: metadata.name,
            description: metadata.description,
          },
        });
      }

      const roles = await tx.posAccessRole.findMany({
        where: {
          code: {
            in: [
              PosAccessRoleCode.CASHIER,
              PosAccessRoleCode.ACCOUNTANT,
              PosAccessRoleCode.KITCHEN,
              PosAccessRoleCode.WAITER,
              PosAccessRoleCode.MARKET_CASHIER,
              PosAccessRoleCode.MARKET_REP,
            ],
          },
        },
        select: { id: true, code: true },
      });
      const permissions = await tx.posPermission.findMany({
        where: { code: { in: ALL_POS_PERMISSION_CODES } },
        select: { id: true, code: true },
      });

      const roleIdByCode = new Map(roles.map((role) => [role.code, role.id]));
      const permissionIdByCode = new Map(permissions.map((permission) => [permission.code, permission.id]));

      for (const [roleCode, permissionCodes] of Object.entries(POS_ROLE_PERMISSIONS) as Array<
        [PosAccessRoleCode, PosPermissionCode[]]
      >) {
        const roleId = roleIdByCode.get(roleCode);
        if (!roleId) {
          continue;
        }

        for (const permissionCode of permissionCodes) {
          const permissionId = permissionIdByCode.get(permissionCode);
          if (!permissionId) {
            continue;
          }

          await tx.posAccessRolePermission.upsert({
            where: {
              roleId_permissionId: {
                roleId,
                permissionId,
              },
            },
            update: {},
            create: {
              roleId,
              permissionId,
            },
          });
        }
      }
    });
  }

  private async ensurePosAccessRoleEnumValues() {
    await this.prisma.$executeRawUnsafe(
      `ALTER TYPE "PosAccessRoleCode" ADD VALUE IF NOT EXISTS 'KITCHEN'`,
    );
    await this.prisma.$executeRawUnsafe(
      `ALTER TYPE "PosAccessRoleCode" ADD VALUE IF NOT EXISTS 'WAITER'`,
    );
    await this.prisma.$executeRawUnsafe(
      `ALTER TYPE "PosAccessRoleCode" ADD VALUE IF NOT EXISTS 'MARKET_CASHIER'`,
    );
    await this.prisma.$executeRawUnsafe(
      `ALTER TYPE "PosAccessRoleCode" ADD VALUE IF NOT EXISTS 'MARKET_REP'`,
    );
    await this.prisma.$executeRawUnsafe(
      `ALTER TYPE "PosPermissionCode" ADD VALUE IF NOT EXISTS 'POS_MARKET_VIEW_RECEIVABLES'`,
    );
    await this.prisma.$executeRawUnsafe(
      `ALTER TYPE "PosPermissionCode" ADD VALUE IF NOT EXISTS 'POS_MARKET_COLLECT_RECEIVABLE'`,
    );
    await this.prisma.$executeRawUnsafe(
      `ALTER TYPE "PosPermissionCode" ADD VALUE IF NOT EXISTS 'POS_MARKET_MANAGE_REP_LOADS'`,
    );
    await this.prisma.$executeRawUnsafe(
      `ALTER TYPE "PosPermissionCode" ADD VALUE IF NOT EXISTS 'POS_MARKET_REP_STOCKTAKE'`,
    );
    await this.prisma.$executeRawUnsafe(
      `ALTER TYPE "PosPermissionCode" ADD VALUE IF NOT EXISTS 'POS_MARKET_AMEND_SALE'`,
    );
  }

  private buildAuthorizedUser(user: Prisma.UserGetPayload<{ include: ReturnType<AuthService['userAccessInclude']> }>): AuthorizedUser {
    const assignedPosRoles = user.posAccessRoles.map(
      (assignment) => assignment.role.code as AuthorizedUser["posRoles"][number],
    );
    const posRoles: AuthorizedUser["posRoles"] = assignedPosRoles.length
      ? assignedPosRoles
      : ["ACCOUNTANT"];

    const permissionSet = new Set<AuthorizedUser['permissions'][number]>();
    for (const assignment of user.posAccessRoles) {
      for (const rolePermission of assignment.role.permissions) {
        permissionSet.add(rolePermission.permission.code as AuthorizedUser['permissions'][number]);
      }
    }

    if (!user.posAccessRoles.length) {
      for (const permissionCode of ACCOUNTANT_PERMISSION_CODES) {
        permissionSet.add(permissionCode);
      }
    }

    const allowedRoutes = uniqueRoutes(
      posRoles.flatMap((roleCode: AuthorizedUser["posRoles"][number]) => POS_ROLE_ROUTE_ACCESS[roleCode]).concat(
        user.role === UserRole.ADMIN || user.role === UserRole.MANAGER || posRoles.includes("ACCOUNTANT")
          ? ["/accounts", "/bank-cash-accounts", "/bank-reconciliations", "/sales-receivables", "/purchases", "/inventory", "/reporting", "/journal-entries", "/general-ledger", "/master-data", "/fiscal", "/audit", "/settings", "/dashboard"]
          : [],
      ),
    );

    const isKitchenOnly =
      posRoles.includes("KITCHEN") &&
      !posRoles.includes("CASHIER") &&
      !posRoles.includes("ACCOUNTANT") &&
      !posRoles.includes("WAITER");
    const isWaiterOnly =
      posRoles.includes("WAITER") &&
      !posRoles.includes("CASHIER") &&
      !posRoles.includes("ACCOUNTANT") &&
      !posRoles.includes("KITCHEN");
    const isMarketCashierOnly =
      posRoles.includes("MARKET_CASHIER") &&
      !posRoles.includes("MARKET_REP") &&
      !posRoles.includes("CASHIER") &&
      !posRoles.includes("ACCOUNTANT") &&
      !posRoles.includes("KITCHEN") &&
      !posRoles.includes("WAITER");
    const isMarketRepOnly =
      posRoles.includes("MARKET_REP") &&
      !posRoles.includes("MARKET_CASHIER") &&
      !posRoles.includes("CASHIER") &&
      !posRoles.includes("ACCOUNTANT") &&
      !posRoles.includes("KITCHEN") &&
      !posRoles.includes("WAITER");
    const isMarketPosOperatorOnly = isMarketCashierOnly || isMarketRepOnly;
    const isCashierOnly =
      posRoles.includes("CASHIER") &&
      !posRoles.includes("MARKET_CASHIER") &&
      !posRoles.includes("MARKET_REP") &&
      !posRoles.includes("ACCOUNTANT") &&
      !posRoles.includes("KITCHEN") &&
      !posRoles.includes("WAITER");
    const defaultRoute = isKitchenOnly
      ? "/dashboard"
      : isWaiterOnly
        ? "/pos/waiter/tables"
        : isMarketRepOnly
          ? "/pos-market/receivables"
          : isMarketCashierOnly
            ? "/pos-market/register"
            : isCashierOnly
              ? "/pos/register"
              : "/dashboard";

    return {
      userId: user.id,
      username: user.username,
      email: user.email,
      name: user.name,
      role: user.role,
      isActive: user.isActive,
      posRoles,
      permissions: Array.from(permissionSet),
      allowedRoutes,
      defaultRoute,
      isCashierOnly,
      isMarketCashierOnly,
      isMarketRepOnly,
      isMarketPosOperatorOnly,
      salesRepId: user.salesRepId ?? null,
      isKitchenOnly,
      isWaiterOnly,
    };
  }

  private userAccessInclude() {
    return {
      posAccessRoles: {
        include: {
          role: {
            include: {
              permissions: {
                include: {
                  permission: true,
                },
              },
            },
          },
        },
      },
    } satisfies Prisma.UserInclude;
  }
}
