CREATE TABLE "PosRuntimeSetting" (
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PosRuntimeSetting_pkey" PRIMARY KEY ("key")
);

INSERT INTO "PosRuntimeSetting" ("key", "value", "createdAt", "updatedAt")
VALUES
    ('POS_POSTING_MODE', 'BY_SESSION', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('POS_COGS_POSTING_ENABLED', 'false', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;
